# Generated by Django 4.1.7 on 2023-03-07 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooler_math_games', '0002_alter_gamescores_date_obtained'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescores',
            name='date_obtained',
            field=models.DateField(default=datetime.datetime(2023, 3, 7, 15, 37, 2, 935839, tzinfo=datetime.timezone.utc)),
        ),
    ]
